import type { CreatorCatalogo } from "@/lib/empresa/creator-catalogo-types";
import type {
  DiaSemana,
  DisponibilidadeInfluenciador,
  TipoAtuacao,
} from "@/lib/types/influenciador";

import { INFLUENCIADOR_MOCK_ID } from "@/lib/mock-data/avaliacoes";

type CreatorCatalogoBase = Omit<
  CreatorCatalogo,
  "tiposAtuacao" | "disponibilidade"
>;

/**
 * Catálogo mock para busca ativa de creators.
 * Apenas status "ativo" devem aparecer na UI (filtrado em listarCreatorsAtivos).
 */
const CREATORS_CATALOGO_BASE: CreatorCatalogoBase[] = [
  {
    id: INFLUENCIADOR_MOCK_ID,
    usuarioId: "usr-influ-neg-001",
    nome: "Ana Beatriz Silva",
    handle: "@anabeauty",
    bio: "Skincare realista, rotinas e lançamentos de beleza com foco em pele sensível.",
    fotoUrl: null,
    nichoId: "cat-beleza",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 128000,
    engajamentoMedio: 4.8,
    precoPacoteMin: 1800,
    notaMediaAvaliacao: 4.9,
    totalAvaliacoes: 23,
    status: "ativo",
  },
  {
    id: "inf-cat-002",
    usuarioId: "usr-cat-002",
    nome: "Bruno Fit Costa",
    handle: "@brunofit",
    bio: "Treinos em casa, suplementação e motivação diária para quem vive corrido.",
    fotoUrl: null,
    nichoId: "cat-fitness",
    cidade: "Curitiba",
    estado: "PR",
    seguidores: 89000,
    engajamentoMedio: 5.2,
    precoPacoteMin: 2200,
    notaMediaAvaliacao: 4.7,
    totalAvaliacoes: 18,
    status: "ativo",
  },
  {
    id: "inf-cat-003",
    usuarioId: "usr-cat-003",
    nome: "Carla Mendes",
    handle: "@carlamodes",
    bio: "Looks acessíveis, thrift e tendência streetwear com toque editorial.",
    fotoUrl: null,
    nichoId: "cat-moda",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    seguidores: 210000,
    engajamentoMedio: 3.4,
    precoPacoteMin: 3500,
    notaMediaAvaliacao: 4.5,
    totalAvaliacoes: 41,
    status: "ativo",
  },
  {
    id: "inf-cat-004",
    usuarioId: "usr-cat-004",
    nome: "Diego Tech",
    handle: "@diegotech",
    bio: "Reviews honestos de gadgets, produtividade e setup de home office.",
    fotoUrl: null,
    nichoId: "cat-tecnologia",
    cidade: "Belo Horizonte",
    estado: "MG",
    seguidores: 156000,
    engajamentoMedio: 4.1,
    precoPacoteMin: 2800,
    notaMediaAvaliacao: 4.8,
    totalAvaliacoes: 31,
    status: "ativo",
  },
  {
    id: "inf-cat-005",
    usuarioId: "usr-cat-005",
    nome: "Elena Cozinha",
    handle: "@elenacozinha",
    bio: "Receitas rápidas, airfryer e jantares de semana sem mistério.",
    fotoUrl: null,
    nichoId: "cat-culinaria",
    cidade: "Porto Alegre",
    estado: "RS",
    seguidores: 67000,
    engajamentoMedio: 6.1,
    precoPacoteMin: 1500,
    notaMediaAvaliacao: 4.6,
    totalAvaliacoes: 12,
    status: "ativo",
  },
  {
    id: "inf-cat-006",
    usuarioId: "usr-cat-006",
    nome: "Felipe Games",
    handle: "@lipegamer",
    bio: "Gameplay, unboxing de consoles e dicas para quem joga no PC.",
    fotoUrl: null,
    nichoId: "cat-games",
    cidade: "Recife",
    estado: "PE",
    seguidores: 340000,
    engajamentoMedio: 2.9,
    precoPacoteMin: 4200,
    notaMediaAvaliacao: 4.3,
    totalAvaliacoes: 56,
    status: "ativo",
  },
  {
    id: "inf-cat-007",
    usuarioId: "usr-cat-007",
    nome: "Giulia Mama",
    handle: "@giuliamama",
    bio: "Maternidade sem filtro, rotina com bebê e produtos que realmente ajudam.",
    fotoUrl: null,
    nichoId: "cat-maternidade",
    cidade: "Campinas",
    estado: "SP",
    seguidores: 54000,
    engajamentoMedio: 7.2,
    precoPacoteMin: 1200,
    notaMediaAvaliacao: 4.9,
    totalAvaliacoes: 9,
    status: "ativo",
  },
  {
    id: "inf-cat-008",
    usuarioId: "usr-cat-008",
    nome: "Hugo Finanças",
    handle: "@hugofinancas",
    bio: "Educação financeira descomplicada, investimentos e organização do mês.",
    fotoUrl: null,
    nichoId: "cat-financas",
    cidade: "Brasília",
    estado: "DF",
    seguidores: 98000,
    engajamentoMedio: 3.8,
    precoPacoteMin: 2500,
    notaMediaAvaliacao: 4.4,
    totalAvaliacoes: 15,
    status: "ativo",
  },
  {
    id: "inf-cat-009",
    usuarioId: "usr-cat-009",
    nome: "Iris Verde",
    handle: "@irisverde",
    bio: "Sustentabilidade no dia a dia, consumo consciente e marcas com propósito.",
    fotoUrl: null,
    nichoId: "cat-sustentabilidade",
    cidade: "Florianópolis",
    estado: "SC",
    seguidores: 41000,
    engajamentoMedio: 5.6,
    precoPacoteMin: 1100,
    notaMediaAvaliacao: null,
    totalAvaliacoes: 2,
    status: "ativo",
  },
  {
    id: "inf-cat-010",
    usuarioId: "usr-cat-010",
    nome: "João Pets",
    handle: "@joaopets",
    bio: "Cães, gatos e dicas de bem-estar animal com humor leve.",
    fotoUrl: null,
    nichoId: "cat-pets",
    cidade: "Goiânia",
    estado: "GO",
    seguidores: 72000,
    engajamentoMedio: 4.9,
    precoPacoteMin: 900,
    notaMediaAvaliacao: null,
    totalAvaliacoes: 1,
    status: "ativo",
  },
  {
    id: "inf-cat-011",
    usuarioId: "usr-cat-011",
    nome: "Karen Viagem",
    handle: "@karenviaja",
    bio: "Roteiros econômicos, hospedagens e destinos no Brasil e América do Sul.",
    fotoUrl: null,
    nichoId: "cat-viagem",
    cidade: "Salvador",
    estado: "BA",
    seguidores: 185000,
    engajamentoMedio: 3.2,
    precoPacoteMin: 3200,
    notaMediaAvaliacao: 4.6,
    totalAvaliacoes: 27,
    status: "ativo",
  },
  {
    id: "inf-cat-012",
    usuarioId: "usr-cat-012",
    nome: "Leo Humor",
    handle: "@leohumor",
    bio: "Sketches do cotidiano, trends e conteúdo viral com humor brasileiro.",
    fotoUrl: null,
    nichoId: "cat-humor",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 520000,
    engajamentoMedio: 2.4,
    precoPacoteMin: 5500,
    notaMediaAvaliacao: 4.2,
    totalAvaliacoes: 64,
    status: "ativo",
  },
  {
    id: "inf-cat-013",
    usuarioId: "usr-cat-013",
    nome: "Marina Saúde",
    handle: "@marinasaude",
    bio: "Bem-estar, sono, alimentação e hábitos sem radicalismo.",
    fotoUrl: null,
    nichoId: "cat-saude",
    cidade: "Niterói",
    estado: "RJ",
    seguidores: 63000,
    engajamentoMedio: 5.0,
    precoPacoteMin: 1600,
    notaMediaAvaliacao: 4.7,
    totalAvaliacoes: 11,
    status: "ativo",
  },
  {
    id: "inf-cat-014",
    usuarioId: "usr-cat-014",
    nome: "Nico Decor",
    handle: "@nicodecor",
    bio: "Antes e depois, DIY e decoração acessível para apartamentos pequenos.",
    fotoUrl: null,
    nichoId: "cat-decoracao",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 112000,
    engajamentoMedio: 3.9,
    precoPacoteMin: 2000,
    notaMediaAvaliacao: 4.5,
    totalAvaliacoes: 19,
    status: "ativo",
  },
  {
    id: "inf-cat-015",
    usuarioId: "usr-cat-015",
    nome: "Olivia Educa",
    handle: "@oliviaeduca",
    bio: "Estudos, concursos e organização de rotina para quem quer evoluir.",
    fotoUrl: null,
    nichoId: "cat-educacao",
    cidade: "Fortaleza",
    estado: "CE",
    seguidores: 48000,
    engajamentoMedio: 6.4,
    precoPacoteMin: 1000,
    notaMediaAvaliacao: null,
    totalAvaliacoes: 0,
    status: "ativo",
  },
  {
    id: "inf-cat-016",
    usuarioId: "usr-cat-016",
    nome: "Pedro Motors",
    handle: "@pedromotors",
    bio: "Carros, lançamentos e comparativos honestos para o motorista brasileiro.",
    fotoUrl: null,
    nichoId: "cat-automotivo",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 275000,
    engajamentoMedio: 2.7,
    precoPacoteMin: 4800,
    notaMediaAvaliacao: 4.1,
    totalAvaliacoes: 38,
    status: "ativo",
  },
  {
    id: "inf-cat-017",
    usuarioId: "usr-cat-017",
    nome: "Quésia Run",
    handle: "@quesiarun",
    bio: "Corrida de rua, treinos e comunidade feminina no esporte.",
    fotoUrl: null,
    nichoId: "cat-esportes",
    cidade: "Londrina",
    estado: "PR",
    seguidores: 36000,
    engajamentoMedio: 8.1,
    precoPacoteMin: 800,
    notaMediaAvaliacao: 4.8,
    totalAvaliacoes: 7,
    status: "ativo",
  },
  {
    id: "inf-cat-018",
    usuarioId: "usr-cat-018",
    nome: "Rafa Beats",
    handle: "@rafabeats",
    bio: "Música indie, playlists e bastidores de shows e estúdio.",
    fotoUrl: null,
    nichoId: "cat-musica",
    cidade: "Belo Horizonte",
    estado: "MG",
    seguidores: 91000,
    engajamentoMedio: 4.3,
    precoPacoteMin: 1700,
    notaMediaAvaliacao: 4.4,
    totalAvaliacoes: 14,
    status: "ativo",
  },
  {
    id: "inf-cat-019",
    usuarioId: "usr-cat-019",
    nome: "Sofia Séries",
    handle: "@sofiaseries",
    bio: "Reviews de séries, spoiler-free e recomendações por humor do dia.",
    fotoUrl: null,
    nichoId: "cat-cinema",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 143000,
    engajamentoMedio: 3.6,
    precoPacoteMin: 2100,
    notaMediaAvaliacao: 4.6,
    totalAvaliacoes: 22,
    status: "ativo",
  },
  {
    id: "inf-cat-020",
    usuarioId: "usr-cat-020",
    nome: "Tiago Empreende",
    handle: "@tiagoempreende",
    bio: "Negócios digitais, rotina de founder e bastidores de crescimento.",
    fotoUrl: null,
    nichoId: "cat-empreendedorismo",
    cidade: "São Paulo",
    estado: "SP",
    seguidores: 76000,
    engajamentoMedio: 4.0,
    precoPacoteMin: 2400,
    notaMediaAvaliacao: 4.5,
    totalAvaliacoes: 16,
    status: "ativo",
  },
  {
    id: "inf-cat-021",
    usuarioId: "usr-cat-021",
    nome: "Úrsula Glow",
    handle: "@ursulaglow",
    bio: "Maquiagem clean, tutoriais rápidos e produtos drugstore testados.",
    fotoUrl: null,
    nichoId: "cat-beleza",
    cidade: "Ribeirão Preto",
    estado: "SP",
    seguidores: 29000,
    engajamentoMedio: 7.8,
    precoPacoteMin: 700,
    notaMediaAvaliacao: null,
    totalAvaliacoes: 0,
    status: "ativo",
  },
  {
    id: "inf-cat-022",
    usuarioId: "usr-cat-022",
    nome: "Vitor Yoga",
    handle: "@vitoryoga",
    bio: "Yoga para iniciantes, respiração e pausas no home office.",
    fotoUrl: null,
    nichoId: "cat-saude",
    cidade: "Vitória",
    estado: "ES",
    seguidores: 22000,
    engajamentoMedio: 9.2,
    precoPacoteMin: 650,
    notaMediaAvaliacao: null,
    totalAvaliacoes: 2,
    status: "ativo",
  },
  {
    id: "inf-cat-023",
    usuarioId: "usr-cat-023",
    nome: "Wanda Street",
    handle: "@wandastreet",
    bio: "Moda plus size, autoconfiança e looks para o dia a dia urbano.",
    fotoUrl: null,
    nichoId: "cat-moda",
    cidade: "Belém",
    estado: "PA",
    seguidores: 118000,
    engajamentoMedio: 4.4,
    precoPacoteMin: 1900,
    notaMediaAvaliacao: 4.8,
    totalAvaliacoes: 20,
    status: "ativo",
  },
  {
    id: "inf-cat-024",
    usuarioId: "usr-cat-024",
    nome: "Yuri Code",
    handle: "@yuricode",
    bio: "Carreira em tech, ferramentas no-code e dicas para juniors.",
    fotoUrl: null,
    nichoId: "cat-tecnologia",
    cidade: "Joinville",
    estado: "SC",
    seguidores: 58000,
    engajamentoMedio: 5.5,
    precoPacoteMin: 1400,
    notaMediaAvaliacao: 4.7,
    totalAvaliacoes: 8,
    status: "ativo",
  },
];

type AtuacaoOverride = {
  tiposAtuacao: TipoAtuacao[];
  disponibilidade?: DisponibilidadeInfluenciador;
};

/** Alguns só modelo, outros híbridos — para testar o toggle Influenciador / Modelo / Todos. */
const ATUACAO_POR_ID: Record<string, AtuacaoOverride> = {
  [INFLUENCIADOR_MOCK_ID]: {
    tiposAtuacao: ["influenciador", "modelo"],
    disponibilidade: {
      diasSemana: ["seg", "ter", "qua", "qui"] as DiaSemana[],
      observacao: "Ensaios em SP capital",
    },
  },
  "inf-cat-003": {
    tiposAtuacao: ["influenciador", "modelo"],
    disponibilidade: {
      diasSemana: ["ter", "qui", "sab"] as DiaSemana[],
    },
  },
  "inf-cat-005": {
    tiposAtuacao: ["modelo"],
    disponibilidade: {
      diasSemana: ["seg", "qua", "sex"] as DiaSemana[],
      observacao: "Disponível para food styling e aparições",
    },
  },
  "inf-cat-007": {
    tiposAtuacao: ["influenciador", "modelo"],
    disponibilidade: {
      diasSemana: ["seg", "ter", "qua", "qui", "sex"] as DiaSemana[],
    },
  },
  "inf-cat-013": {
    tiposAtuacao: ["modelo"],
    disponibilidade: {
      diasSemana: ["sab", "dom"] as DiaSemana[],
    },
  },
  "inf-cat-017": {
    tiposAtuacao: ["influenciador", "modelo"],
    disponibilidade: {
      diasSemana: ["qua", "qui", "sex", "sab"] as DiaSemana[],
    },
  },
  "inf-cat-021": {
    tiposAtuacao: ["modelo"],
    disponibilidade: {
      diasSemana: ["ter", "qua", "qui"] as DiaSemana[],
      observacao: "Foco em beauty e moda editorial",
    },
  },
  "inf-cat-023": {
    tiposAtuacao: ["influenciador", "modelo"],
    disponibilidade: {
      diasSemana: ["seg", "sex", "sab"] as DiaSemana[],
    },
  },
};

export const CREATORS_CATALOGO_MOCK: CreatorCatalogo[] =
  CREATORS_CATALOGO_BASE.map((c) => {
    const override = ATUACAO_POR_ID[c.id];
    return {
      ...c,
      tiposAtuacao: override?.tiposAtuacao ?? ["influenciador"],
      ...(override?.disponibilidade
        ? { disponibilidade: override.disponibilidade }
        : {}),
    };
  });
